apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: example-daemonset
  labels:
    app: example
spec:
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: example-container
        image: nginx
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
        ports:
        - containerPort: 80



# DaemonSet doesn't have replicas
# This will sindle pod in every node in the cluster
