apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
  containers:
  - name: sample-container
    image: sample-pod1    # this image does not exist on dockerhub we will get an imagepullbackofferror
    # image: nginx2213
    imagePullPolicy: Always