# This deployment attempts to run a container that requires a dependency not present in the container image.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: missing-dependencies-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: missing-dependencies
  template:
    metadata:
      labels:
        app: missing-dependencies
    spec:
      containers:
      - name: missing-dependencies-container
        image: alpine
        command: ["sh", "-c", "apk add --no-cache redis && redis-server"]
