apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: front-end-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front-end-ui
  template:
    metadata:
      labels:
        app: front-end-ui
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 80