apiVersion: v1
kind: Service
metadata:
  name: multi-port-service-service
spec:
  selector:
    app: front-end-ui
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
    - name: https
      protocol: TCP
      port: 8081
      targetPort: 81